#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This file is an import-only file providing a mechanism for other files to
# import a range of modules in a controlled way. It could be made to pass
# flake8 but given its simplicity it is being marked as noqa for now.
#
# flake8: noqa

from omero import ObjectFactoryRegistrar
from typing import TYPE_CHECKING

import IceImport

if TYPE_CHECKING:
    from omero_model_AcquisitionModeI import AcquisitionModeI
    from omero_model_AdminPrivilegeI import AdminPrivilegeI
    from omero_model_AffineTransformI import AffineTransformI
    from omero_model_AnnotationAnnotationLinkI import AnnotationAnnotationLinkI
    from omero_model_ArcI import ArcI
    from omero_model_ArcTypeI import ArcTypeI
    from omero_model_BinningI import BinningI
    from omero_model_BooleanAnnotationI import BooleanAnnotationI
    from omero_model_ChannelAnnotationLinkI import ChannelAnnotationLinkI
    from omero_model_ChannelBindingI import ChannelBindingI
    from omero_model_ChannelI import ChannelI
    from omero_model_ChecksumAlgorithmI import ChecksumAlgorithmI
    from omero_model_CommentAnnotationI import CommentAnnotationI
    from omero_model_ContrastMethodI import ContrastMethodI
    from omero_model_ContrastStretchingContextI import ContrastStretchingContextI
    from omero_model_CorrectionI import CorrectionI
    from omero_model_DBPatchI import DBPatchI
    from omero_model_DatasetAnnotationLinkI import DatasetAnnotationLinkI
    from omero_model_DatasetI import DatasetI
    from omero_model_DatasetImageLinkI import DatasetImageLinkI
    from omero_model_DetailsI import DetailsI
    from omero_model_DetectorAnnotationLinkI import DetectorAnnotationLinkI
    from omero_model_DetectorI import DetectorI
    from omero_model_DetectorSettingsI import DetectorSettingsI
    from omero_model_DetectorTypeI import DetectorTypeI
    from omero_model_DichroicAnnotationLinkI import DichroicAnnotationLinkI
    from omero_model_DichroicI import DichroicI
    from omero_model_DimensionOrderI import DimensionOrderI
    from omero_model_DoubleAnnotationI import DoubleAnnotationI
    from omero_model_ElectricPotentialI import ElectricPotentialI
    from omero_model_EllipseI import EllipseI
    from omero_model_EventI import EventI
    from omero_model_EventLogI import EventLogI
    from omero_model_EventTypeI import EventTypeI
    from omero_model_ExperimentI import ExperimentI
    from omero_model_ExperimentTypeI import ExperimentTypeI
    from omero_model_ExperimenterAnnotationLinkI import ExperimenterAnnotationLinkI
    from omero_model_ExperimenterGroupAnnotationLinkI import ExperimenterGroupAnnotationLinkI
    from omero_model_ExperimenterGroupI import ExperimenterGroupI
    from omero_model_ExperimenterI import ExperimenterI
    from omero_model_ExternalInfoI import ExternalInfoI
    from omero_model_FamilyI import FamilyI
    from omero_model_FilamentI import FilamentI
    from omero_model_FilamentTypeI import FilamentTypeI
    from omero_model_FileAnnotationI import FileAnnotationI
    from omero_model_FilesetAnnotationLinkI import FilesetAnnotationLinkI
    from omero_model_FilesetEntryI import FilesetEntryI
    from omero_model_FilesetI import FilesetI
    from omero_model_FilesetJobLinkI import FilesetJobLinkI
    from omero_model_FilterAnnotationLinkI import FilterAnnotationLinkI
    from omero_model_FilterI import FilterI
    from omero_model_FilterSetEmissionFilterLinkI import FilterSetEmissionFilterLinkI
    from omero_model_FilterSetExcitationFilterLinkI import FilterSetExcitationFilterLinkI
    from omero_model_FilterSetI import FilterSetI
    from omero_model_FilterTypeI import FilterTypeI
    from omero_model_FolderAnnotationLinkI import FolderAnnotationLinkI
    from omero_model_FolderI import FolderI
    from omero_model_FolderImageLinkI import FolderImageLinkI
    from omero_model_FolderRoiLinkI import FolderRoiLinkI
    from omero_model_FormatI import FormatI
    from omero_model_FrequencyI import FrequencyI
    from omero_model_GenericExcitationSourceI import GenericExcitationSourceI
    from omero_model_GroupExperimenterMapI import GroupExperimenterMapI
    from omero_model_IlluminationI import IlluminationI
    from omero_model_ImageAnnotationLinkI import ImageAnnotationLinkI
    from omero_model_ImageI import ImageI
    from omero_model_ImagingEnvironmentI import ImagingEnvironmentI
    from omero_model_ImmersionI import ImmersionI
    from omero_model_ImportJobI import ImportJobI
    from omero_model_IndexingJobI import IndexingJobI
    from omero_model_InstrumentAnnotationLinkI import InstrumentAnnotationLinkI
    from omero_model_InstrumentI import InstrumentI
    from omero_model_IntegrityCheckJobI import IntegrityCheckJobI
    from omero_model_JobI import JobI
    from omero_model_JobOriginalFileLinkI import JobOriginalFileLinkI
    from omero_model_JobStatusI import JobStatusI
    from omero_model_LabelI import LabelI
    from omero_model_LaserI import LaserI
    from omero_model_LaserMediumI import LaserMediumI
    from omero_model_LaserTypeI import LaserTypeI
    from omero_model_LengthI import LengthI
    from omero_model_LightEmittingDiodeI import LightEmittingDiodeI
    from omero_model_LightPathAnnotationLinkI import LightPathAnnotationLinkI
    from omero_model_LightPathEmissionFilterLinkI import LightPathEmissionFilterLinkI
    from omero_model_LightPathExcitationFilterLinkI import LightPathExcitationFilterLinkI
    from omero_model_LightPathI import LightPathI
    from omero_model_LightSettingsI import LightSettingsI
    from omero_model_LightSourceAnnotationLinkI import LightSourceAnnotationLinkI
    from omero_model_LinkI import LinkI
    from omero_model_ListAnnotationI import ListAnnotationI
    from omero_model_LogicalChannelI import LogicalChannelI
    from omero_model_LongAnnotationI import LongAnnotationI
    from omero_model_MapAnnotationI import MapAnnotationI
    from omero_model_MaskI import MaskI
    from omero_model_MediumI import MediumI
    from omero_model_MetadataImportJobI import MetadataImportJobI
    from omero_model_MicrobeamManipulationI import MicrobeamManipulationI
    from omero_model_MicrobeamManipulationTypeI import MicrobeamManipulationTypeI
    from omero_model_MicroscopeI import MicroscopeI
    from omero_model_MicroscopeTypeI import MicroscopeTypeI
    from omero_model_NamespaceAnnotationLinkI import NamespaceAnnotationLinkI
    from omero_model_NamespaceI import NamespaceI
    from omero_model_NodeAnnotationLinkI import NodeAnnotationLinkI
    from omero_model_NodeI import NodeI
    from omero_model_OTFI import OTFI
    from omero_model_ObjectiveAnnotationLinkI import ObjectiveAnnotationLinkI
    from omero_model_ObjectiveI import ObjectiveI
    from omero_model_ObjectiveSettingsI import ObjectiveSettingsI
    from omero_model_OriginalFileAnnotationLinkI import OriginalFileAnnotationLinkI
    from omero_model_OriginalFileI import OriginalFileI
    from omero_model_ParseJobI import ParseJobI
    from omero_model_PathI import PathI
    from omero_model_PermissionsI import PermissionsI
    from omero_model_PhotometricInterpretationI import PhotometricInterpretationI
    from omero_model_PixelDataJobI import PixelDataJobI
    from omero_model_PixelsI import PixelsI
    from omero_model_PixelsOriginalFileMapI import PixelsOriginalFileMapI
    from omero_model_PixelsTypeI import PixelsTypeI
    from omero_model_PlaneInfoAnnotationLinkI import PlaneInfoAnnotationLinkI
    from omero_model_PlaneInfoI import PlaneInfoI
    from omero_model_PlaneSlicingContextI import PlaneSlicingContextI
    from omero_model_PlateAcquisitionAnnotationLinkI import PlateAcquisitionAnnotationLinkI
    from omero_model_PlateAcquisitionI import PlateAcquisitionI
    from omero_model_PlateAnnotationLinkI import PlateAnnotationLinkI
    from omero_model_PlateI import PlateI
    from omero_model_PointI import PointI
    from omero_model_PolygonI import PolygonI
    from omero_model_PolylineI import PolylineI
    from omero_model_PowerI import PowerI
    from omero_model_PressureI import PressureI
    from omero_model_ProjectAnnotationLinkI import ProjectAnnotationLinkI
    from omero_model_ProjectDatasetLinkI import ProjectDatasetLinkI
    from omero_model_ProjectI import ProjectI
    from omero_model_ProjectionAxisI import ProjectionAxisI
    from omero_model_ProjectionDefI import ProjectionDefI
    from omero_model_ProjectionTypeI import ProjectionTypeI
    from omero_model_PulseI import PulseI
    from omero_model_QuantumDefI import QuantumDefI
    from omero_model_ReagentAnnotationLinkI import ReagentAnnotationLinkI
    from omero_model_ReagentI import ReagentI
    from omero_model_RectangleI import RectangleI
    from omero_model_RenderingDefI import RenderingDefI
    from omero_model_RenderingModelI import RenderingModelI
    from omero_model_ReverseIntensityContextI import ReverseIntensityContextI
    from omero_model_RoiAnnotationLinkI import RoiAnnotationLinkI
    from omero_model_RoiI import RoiI
    from omero_model_ScreenAnnotationLinkI import ScreenAnnotationLinkI
    from omero_model_ScreenI import ScreenI
    from omero_model_ScreenPlateLinkI import ScreenPlateLinkI
    from omero_model_ScriptJobI import ScriptJobI
    from omero_model_SessionAnnotationLinkI import SessionAnnotationLinkI
    from omero_model_SessionI import SessionI
    from omero_model_ShapeAnnotationLinkI import ShapeAnnotationLinkI
    from omero_model_ShareI import ShareI
    from omero_model_ShareMemberI import ShareMemberI
    from omero_model_StageLabelI import StageLabelI
    from omero_model_StatsInfoI import StatsInfoI
    from omero_model_TagAnnotationI import TagAnnotationI
    from omero_model_TemperatureI import TemperatureI
    from omero_model_TermAnnotationI import TermAnnotationI
    from omero_model_ThumbnailGenerationJobI import ThumbnailGenerationJobI
    from omero_model_ThumbnailI import ThumbnailI
    from omero_model_TimeI import TimeI
    from omero_model_TimestampAnnotationI import TimestampAnnotationI
    from omero_model_TransmittanceRangeI import TransmittanceRangeI
    from omero_model_UploadJobI import UploadJobI
    from omero_model_WellAnnotationLinkI import WellAnnotationLinkI
    from omero_model_WellI import WellI
    from omero_model_WellReagentLinkI import WellReagentLinkI
    from omero_model_WellSampleI import WellSampleI
    from omero_model_XmlAnnotationI import XmlAnnotationI

IceImport.load("omero_model_NamedValue_ice")
