import Ice
from typing import ClassVar

AcquisitionModeBrightField: str
AcquisitionModeFSM: str
AcquisitionModeFluorescenceCorrelationSpectroscopy: str
AcquisitionModeFluorescenceLifetime: str
AcquisitionModeLCM: str
AcquisitionModeLaserScanningConfocalMicroscopy: str
AcquisitionModeMultiPhotonMicroscopy: str
AcquisitionModeNearFieldScanningOpticalMicroscopy: str
AcquisitionModeOther: str
AcquisitionModePALM: str
AcquisitionModeSPIM: str
AcquisitionModeSTED: str
AcquisitionModeSTORM: str
AcquisitionModeSecondHarmonicGenerationImaging: str
AcquisitionModeSingleMoleculeImaging: str
AcquisitionModeSlitScanConfocal: str
AcquisitionModeSpectralImaging: str
AcquisitionModeSpinningDiskConfocal: str
AcquisitionModeStructuredIllumination: str
AcquisitionModeSweptFieldConfocal: str
AcquisitionModeTIRF: str
AcquisitionModeTotalInternalReflection: str
AcquisitionModeUnknown: str
AcquisitionModeWideField: str
AdminPrivilegeChgrp: str
AdminPrivilegeChown: str
AdminPrivilegeDeleteFile: str
AdminPrivilegeDeleteManagedRepo: str
AdminPrivilegeDeleteOwned: str
AdminPrivilegeDeleteScriptRepo: str
AdminPrivilegeModifyGroup: str
AdminPrivilegeModifyGroupMembership: str
AdminPrivilegeModifyUser: str
AdminPrivilegeReadSession: str
AdminPrivilegeSudo: str
AdminPrivilegeWriteFile: str
AdminPrivilegeWriteManagedRepo: str
AdminPrivilegeWriteOwned: str
AdminPrivilegeWriteScriptRepo: str
ArcTypeHg: str
ArcTypeHgXe: str
ArcTypeOther: str
ArcTypeUnknown: str
ArcTypeXe: str
Binning1x1: str
Binning2x2: str
Binning4x4: str
Binning8x8: str
ChecksumAlgorithmAdler32: str
ChecksumAlgorithmCRC32: str
ChecksumAlgorithmFileSize64: str
ChecksumAlgorithmMD5128: str
ChecksumAlgorithmMurmur3128: str
ChecksumAlgorithmMurmur332: str
ChecksumAlgorithmSHA1160: str
ContrastMethodBrightfield: str
ContrastMethodDIC: str
ContrastMethodDarkfield: str
ContrastMethodFluorescence: str
ContrastMethodHoffmanModulation: str
ContrastMethodObliqueIllumination: str
ContrastMethodOther: str
ContrastMethodPhase: str
ContrastMethodPolarizedLight: str
ContrastMethodUnknown: str
CorrectionAchro: str
CorrectionAchromat: str
CorrectionApo: str
CorrectionFl: str
CorrectionFluar: str
CorrectionFluor: str
CorrectionFluotar: str
CorrectionNeofluar: str
CorrectionOther: str
CorrectionPlanApo: str
CorrectionPlanFluor: str
CorrectionSuperFluor: str
CorrectionUV: str
CorrectionUnknown: str
CorrectionVioletCorrected: str
DetectorTypeAPD: str
DetectorTypeAnalogVideo: str
DetectorTypeCCD: str
DetectorTypeCMOS: str
DetectorTypeCorrelationSpectroscopy: str
DetectorTypeEBCCD: str
DetectorTypeEMCCD: str
DetectorTypeFTIR: str
DetectorTypeIntensifiedCCD: str
DetectorTypeLifetimeImaging: str
DetectorTypeOther: str
DetectorTypePMT: str
DetectorTypePhotodiode: str
DetectorTypeSpectroscopy: str
DetectorTypeUnknown: str
DimensionOrderXYCTZ: str
DimensionOrderXYCZT: str
DimensionOrderXYTCZ: str
DimensionOrderXYTZC: str
DimensionOrderXYZCT: str
DimensionOrderXYZTC: str
EventTypeFullText: str
EventTypeImport: str
EventTypeInternal: str
EventTypeProcessing: str
EventTypeSessions: str
EventTypeShoola: str
EventTypeTask: str
EventTypeTest: str
EventTypeUser: str
ExperimentTypeColocalization: str
ExperimentTypeElectrophysiology: str
ExperimentTypeFISH: str
ExperimentTypeFP: str
ExperimentTypeFRET: str
ExperimentTypeFluorescenceLifetime: str
ExperimentTypeFourDPlus: str
ExperimentTypeImmunocytochemistry: str
ExperimentTypeImmunofluorescence: str
ExperimentTypeIonImaging: str
ExperimentTypeOther: str
ExperimentTypePGIDocumentation: str
ExperimentTypePhotobleaching: str
ExperimentTypeScreen: str
ExperimentTypeSpectralImaging: str
ExperimentTypeTimeLapse: str
ExperimentTypeUnknown: str
Familyexponential: str
Familylinear: str
Familylogarithmic: str
Familypolynomial: str
FilamentTypeHalogen: str
FilamentTypeIncandescent: str
FilamentTypeOther: str
FilamentTypeUnknown: str
FilterTypeBandPass: str
FilterTypeDichroic: str
FilterTypeLongPass: str
FilterTypeMultiPass: str
FilterTypeNeutralDensity: str
FilterTypeOther: str
FilterTypeShortPass: str
FilterTypeTuneable: str
FilterTypeUnknown: str
IlluminationEpifluorescence: str
IlluminationNonLinear: str
IlluminationOblique: str
IlluminationOther: str
IlluminationTransmitted: str
IlluminationUnknown: str
ImmersionAir: str
ImmersionGlycerol: str
ImmersionMulti: str
ImmersionOil: str
ImmersionOther: str
ImmersionUnknown: str
ImmersionWater: str
ImmersionWaterDipping: str
JobStatusCancelled: str
JobStatusError: str
JobStatusFinished: str
JobStatusQueued: str
JobStatusRequeued: str
JobStatusResubmitted: str
JobStatusRunning: str
JobStatusSubmitted: str
JobStatusWaiting: str
LaserMediumAg: str
LaserMediumAlexandrite: str
LaserMediumAr: str
LaserMediumArCl: str
LaserMediumArFl: str
LaserMediumCO: str
LaserMediumCO2: str
LaserMediumCoumarinC30: str
LaserMediumCu: str
LaserMediumEMinus: str
LaserMediumErGlass: str
LaserMediumErYAG: str
LaserMediumGaAlAs: str
LaserMediumGaAs: str
LaserMediumH2O: str
LaserMediumHFl: str
LaserMediumHeCd: str
LaserMediumHeNe: str
LaserMediumHoYAG: str
LaserMediumHoYLF: str
LaserMediumKr: str
LaserMediumKrCl: str
LaserMediumKrFl: str
LaserMediumN: str
LaserMediumNdGlass: str
LaserMediumNdYAG: str
LaserMediumOther: str
LaserMediumRhodamine6G: str
LaserMediumRuby: str
LaserMediumTiSapphire: str
LaserMediumUnknown: str
LaserMediumXe: str
LaserMediumXeBr: str
LaserMediumXeCl: str
LaserMediumXeFl: str
LaserTypeDye: str
LaserTypeExcimer: str
LaserTypeFreeElectron: str
LaserTypeGas: str
LaserTypeMetalVapor: str
LaserTypeOther: str
LaserTypeSemiconductor: str
LaserTypeSolidState: str
LaserTypeUnknown: str
MediumAir: str
MediumGlycerol: str
MediumOil: str
MediumOther: str
MediumUnknown: str
MediumWater: str
MicrobeamManipulationTypeFLIP: str
MicrobeamManipulationTypeFRAP: str
MicrobeamManipulationTypeInverseFRAP: str
MicrobeamManipulationTypeOpticalTrapping: str
MicrobeamManipulationTypeOther: str
MicrobeamManipulationTypePhotoablation: str
MicrobeamManipulationTypePhotoactivation: str
MicrobeamManipulationTypeUncaging: str
MicrobeamManipulationTypeUnknown: str
MicroscopeTypeDissection: str
MicroscopeTypeElectrophysiology: str
MicroscopeTypeInverted: str
MicroscopeTypeOther: str
MicroscopeTypeUnknown: str
MicroscopeTypeUpright: str
PhotometricInterpretationARGB: str
PhotometricInterpretationCMYK: str
PhotometricInterpretationColorMap: str
PhotometricInterpretationHSV: str
PhotometricInterpretationMonochrome: str
PhotometricInterpretationRGB: str
PixelsTypebit: str
PixelsTypecomplex: str
PixelsTypedouble: str
PixelsTypedoublecomplex: str
PixelsTypefloat: str
PixelsTypeint16: str
PixelsTypeint32: str
PixelsTypeint8: str
PixelsTypeuint16: str
PixelsTypeuint32: str
PixelsTypeuint8: str
ProjectionAxisModuloT: str
ProjectionAxisModuloZ: str
ProjectionAxisT: str
ProjectionAxisZ: str
ProjectionTypemaximum: str
ProjectionTypemean: str
ProjectionTypesum: str
PulseCW: str
PulseModeLocked: str
PulseOther: str
PulseQSwitched: str
PulseRepetitive: str
PulseSingle: str
PulseUnknown: str
RenderingModelgreyscale: str
RenderingModelrgb: str

class UnitsElectricPotential(Ice.EnumBase):
    ATTOVOLT: ClassVar[UnitsElectricPotential] = ...
    CENTIVOLT: ClassVar[UnitsElectricPotential] = ...
    DECAVOLT: ClassVar[UnitsElectricPotential] = ...
    DECIVOLT: ClassVar[UnitsElectricPotential] = ...
    EXAVOLT: ClassVar[UnitsElectricPotential] = ...
    FEMTOVOLT: ClassVar[UnitsElectricPotential] = ...
    GIGAVOLT: ClassVar[UnitsElectricPotential] = ...
    HECTOVOLT: ClassVar[UnitsElectricPotential] = ...
    KILOVOLT: ClassVar[UnitsElectricPotential] = ...
    MEGAVOLT: ClassVar[UnitsElectricPotential] = ...
    MICROVOLT: ClassVar[UnitsElectricPotential] = ...
    MILLIVOLT: ClassVar[UnitsElectricPotential] = ...
    NANOVOLT: ClassVar[UnitsElectricPotential] = ...
    PETAVOLT: ClassVar[UnitsElectricPotential] = ...
    PICOVOLT: ClassVar[UnitsElectricPotential] = ...
    TERAVOLT: ClassVar[UnitsElectricPotential] = ...
    VOLT: ClassVar[UnitsElectricPotential] = ...
    YOCTOVOLT: ClassVar[UnitsElectricPotential] = ...
    YOTTAVOLT: ClassVar[UnitsElectricPotential] = ...
    ZEPTOVOLT: ClassVar[UnitsElectricPotential] = ...
    ZETTAVOLT: ClassVar[UnitsElectricPotential] = ...

class UnitsFrequency(Ice.EnumBase):
    ATTOHERTZ: ClassVar[UnitsFrequency] = ...
    CENTIHERTZ: ClassVar[UnitsFrequency] = ...
    DECAHERTZ: ClassVar[UnitsFrequency] = ...
    DECIHERTZ: ClassVar[UnitsFrequency] = ...
    EXAHERTZ: ClassVar[UnitsFrequency] = ...
    FEMTOHERTZ: ClassVar[UnitsFrequency] = ...
    GIGAHERTZ: ClassVar[UnitsFrequency] = ...
    HECTOHERTZ: ClassVar[UnitsFrequency] = ...
    HERTZ: ClassVar[UnitsFrequency] = ...
    KILOHERTZ: ClassVar[UnitsFrequency] = ...
    MEGAHERTZ: ClassVar[UnitsFrequency] = ...
    MICROHERTZ: ClassVar[UnitsFrequency] = ...
    MILLIHERTZ: ClassVar[UnitsFrequency] = ...
    NANOHERTZ: ClassVar[UnitsFrequency] = ...
    PETAHERTZ: ClassVar[UnitsFrequency] = ...
    PICOHERTZ: ClassVar[UnitsFrequency] = ...
    TERAHERTZ: ClassVar[UnitsFrequency] = ...
    YOCTOHERTZ: ClassVar[UnitsFrequency] = ...
    YOTTAHERTZ: ClassVar[UnitsFrequency] = ...
    ZEPTOHERTZ: ClassVar[UnitsFrequency] = ...
    ZETTAHERTZ: ClassVar[UnitsFrequency] = ...

class UnitsLength(Ice.EnumBase):
    ANGSTROM: ClassVar[UnitsLength] = ...
    ASTRONOMICALUNIT: ClassVar[UnitsLength] = ...
    ATTOMETER: ClassVar[UnitsLength] = ...
    CENTIMETER: ClassVar[UnitsLength] = ...
    DECAMETER: ClassVar[UnitsLength] = ...
    DECIMETER: ClassVar[UnitsLength] = ...
    EXAMETER: ClassVar[UnitsLength] = ...
    FEMTOMETER: ClassVar[UnitsLength] = ...
    FOOT: ClassVar[UnitsLength] = ...
    GIGAMETER: ClassVar[UnitsLength] = ...
    HECTOMETER: ClassVar[UnitsLength] = ...
    INCH: ClassVar[UnitsLength] = ...
    KILOMETER: ClassVar[UnitsLength] = ...
    LIGHTYEAR: ClassVar[UnitsLength] = ...
    LINE: ClassVar[UnitsLength] = ...
    MEGAMETER: ClassVar[UnitsLength] = ...
    METER: ClassVar[UnitsLength] = ...
    MICROMETER: ClassVar[UnitsLength] = ...
    MILE: ClassVar[UnitsLength] = ...
    MILLIMETER: ClassVar[UnitsLength] = ...
    NANOMETER: ClassVar[UnitsLength] = ...
    PARSEC: ClassVar[UnitsLength] = ...
    PETAMETER: ClassVar[UnitsLength] = ...
    PICOMETER: ClassVar[UnitsLength] = ...
    PIXEL: ClassVar[UnitsLength] = ...
    POINT: ClassVar[UnitsLength] = ...
    REFERENCEFRAME: ClassVar[UnitsLength] = ...
    TERAMETER: ClassVar[UnitsLength] = ...
    THOU: ClassVar[UnitsLength] = ...
    YARD: ClassVar[UnitsLength] = ...
    YOCTOMETER: ClassVar[UnitsLength] = ...
    YOTTAMETER: ClassVar[UnitsLength] = ...
    ZEPTOMETER: ClassVar[UnitsLength] = ...
    ZETTAMETER: ClassVar[UnitsLength] = ...

class UnitsPower(Ice.EnumBase):
    ATTOWATT: ClassVar[UnitsPower] = ...
    CENTIWATT: ClassVar[UnitsPower] = ...
    DECAWATT: ClassVar[UnitsPower] = ...
    DECIWATT: ClassVar[UnitsPower] = ...
    EXAWATT: ClassVar[UnitsPower] = ...
    FEMTOWATT: ClassVar[UnitsPower] = ...
    GIGAWATT: ClassVar[UnitsPower] = ...
    HECTOWATT: ClassVar[UnitsPower] = ...
    KILOWATT: ClassVar[UnitsPower] = ...
    MEGAWATT: ClassVar[UnitsPower] = ...
    MICROWATT: ClassVar[UnitsPower] = ...
    MILLIWATT: ClassVar[UnitsPower] = ...
    NANOWATT: ClassVar[UnitsPower] = ...
    PETAWATT: ClassVar[UnitsPower] = ...
    PICOWATT: ClassVar[UnitsPower] = ...
    TERAWATT: ClassVar[UnitsPower] = ...
    WATT: ClassVar[UnitsPower] = ...
    YOCTOWATT: ClassVar[UnitsPower] = ...
    YOTTAWATT: ClassVar[UnitsPower] = ...
    ZEPTOWATT: ClassVar[UnitsPower] = ...
    ZETTAWATT: ClassVar[UnitsPower] = ...

class UnitsPressure(Ice.EnumBase):
    ATMOSPHERE: ClassVar[UnitsPressure] = ...
    ATTOPASCAL: ClassVar[UnitsPressure] = ...
    BAR: ClassVar[UnitsPressure] = ...
    CENTIBAR: ClassVar[UnitsPressure] = ...
    CENTIPASCAL: ClassVar[UnitsPressure] = ...
    DECAPASCAL: ClassVar[UnitsPressure] = ...
    DECIBAR: ClassVar[UnitsPressure] = ...
    DECIPASCAL: ClassVar[UnitsPressure] = ...
    EXAPASCAL: ClassVar[UnitsPressure] = ...
    FEMTOPASCAL: ClassVar[UnitsPressure] = ...
    GIGAPASCAL: ClassVar[UnitsPressure] = ...
    HECTOPASCAL: ClassVar[UnitsPressure] = ...
    KILOBAR: ClassVar[UnitsPressure] = ...
    KILOPASCAL: ClassVar[UnitsPressure] = ...
    MEGABAR: ClassVar[UnitsPressure] = ...
    MEGAPASCAL: ClassVar[UnitsPressure] = ...
    MICROPASCAL: ClassVar[UnitsPressure] = ...
    MILLIBAR: ClassVar[UnitsPressure] = ...
    MILLIPASCAL: ClassVar[UnitsPressure] = ...
    MILLITORR: ClassVar[UnitsPressure] = ...
    MMHG: ClassVar[UnitsPressure] = ...
    NANOPASCAL: ClassVar[UnitsPressure] = ...
    PASCAL: ClassVar[UnitsPressure] = ...
    PETAPASCAL: ClassVar[UnitsPressure] = ...
    PICOPASCAL: ClassVar[UnitsPressure] = ...
    PSI: ClassVar[UnitsPressure] = ...
    TERAPASCAL: ClassVar[UnitsPressure] = ...
    TORR: ClassVar[UnitsPressure] = ...
    YOCTOPASCAL: ClassVar[UnitsPressure] = ...
    YOTTAPASCAL: ClassVar[UnitsPressure] = ...
    ZEPTOPASCAL: ClassVar[UnitsPressure] = ...
    ZETTAPASCAL: ClassVar[UnitsPressure] = ...

class UnitsTemperature(Ice.EnumBase):
    CELSIUS: ClassVar[UnitsTemperature] = ...
    FAHRENHEIT: ClassVar[UnitsTemperature] = ...
    KELVIN: ClassVar[UnitsTemperature] = ...
    RANKINE: ClassVar[UnitsTemperature] = ...

class UnitsTime(Ice.EnumBase):
    ATTOSECOND: ClassVar[UnitsTime] = ...
    CENTISECOND: ClassVar[UnitsTime] = ...
    DAY: ClassVar[UnitsTime] = ...
    DECASECOND: ClassVar[UnitsTime] = ...
    DECISECOND: ClassVar[UnitsTime] = ...
    EXASECOND: ClassVar[UnitsTime] = ...
    FEMTOSECOND: ClassVar[UnitsTime] = ...
    GIGASECOND: ClassVar[UnitsTime] = ...
    HECTOSECOND: ClassVar[UnitsTime] = ...
    HOUR: ClassVar[UnitsTime] = ...
    KILOSECOND: ClassVar[UnitsTime] = ...
    MEGASECOND: ClassVar[UnitsTime] = ...
    MICROSECOND: ClassVar[UnitsTime] = ...
    MILLISECOND: ClassVar[UnitsTime] = ...
    MINUTE: ClassVar[UnitsTime] = ...
    NANOSECOND: ClassVar[UnitsTime] = ...
    PETASECOND: ClassVar[UnitsTime] = ...
    PICOSECOND: ClassVar[UnitsTime] = ...
    SECOND: ClassVar[UnitsTime] = ...
    TERASECOND: ClassVar[UnitsTime] = ...
    YOCTOSECOND: ClassVar[UnitsTime] = ...
    YOTTASECOND: ClassVar[UnitsTime] = ...
    ZEPTOSECOND: ClassVar[UnitsTime] = ...
    ZETTASECOND: ClassVar[UnitsTime] = ...
