name: Publish
on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  # https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
  publish-pypi:
    name: Pypi
    if: startsWith(github.ref, 'refs/tags')
    needs:
      # Only publish if other jobs passed
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Build package
        run: |
          python -mpip install wheel
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.0
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
  update-repository:
    needs:
      - publish-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Extract version and sha256
        run: |
          python -m pip download --no-deps --no-binary :all: omero-py
          output=$(python -m pip hash *.gz)
          hash256=$(echo $output | cut -d':' -f 3)
          package=$(echo $output | cut -d':' -f 1)
          version="${package#*omero-py-}"
          version="${version%.tar.gz}"
          echo "package_sha256="$hash256 >> $GITHUB_ENV
          echo "package_version="$version >> $GITHUB_ENV
          rm *.gz
      - name: Checkout conda-omero-py
        uses: actions/checkout@master
        with:
          repository: ome/conda-omero-py
      - name: Set the version and sha256
        run: |
          sed -i "s/\(.*sha256:.*\)/sha256: ${{env.package_sha256}}/g" meta.yaml
          sed -i "s/\(version = \).*/version = \"${{env.package_version}}\" %}/" meta.yaml
      - name: Create commits
        run: |
          git config user.name 'snoopycrimecop'
          git config user.email 'snoopycrimecop@users.noreply.github.com'
          git add -A
          git commit -m "Update version"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
